[package]
name = "datalog-syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "3.0.0"
rkyv = { version = "0.7.42", features = ["validation"] }
size-of = "0.1.5"